AWSTemplateFormatVersion: 2010-09-09

Parameters: 

Resources: 
  iamUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      UserName: "demo-user"
      Policies:
        policyName: demo-policy
        PolicyDocument:
          Version: "2012-0-17"
          Statment:
            - Effect: "Allow"
              Action: ['cloudforamtion:*']
              Resources: '*'
            
  
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: iamUser 
   
  
 
Outputs:
  AccessKeyId:
    Value:
      Ref: AccessKey
  
  SecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey
  
  User:
    Value: !Ref iamUser
  
