AWSTemplateFormatVersion: 2010-09-09

Description: ---
  This template contains the security groups required by our entire stack.
  We create them in a seperate nested template, so they can be referenced
  by all of the other nested templates.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPC:
    Description: Choose which VPC the security groups should be deployed to
    Type: AWS::EC2::VPC::Id

  IngressCIDR:
    Description: Please enter the IP range (CIDR notation) from which to allow access to APP-Server/RDS Security Groups
    Type: String

Resources:
  AppserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-appserver-security-group
      GroupDescription: appserver security group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref IngressCIDR
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: !Ref IngressCIDR
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: !Ref IngressCIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-appserver

Outputs:
  AppserverSecurityGroup:
    Description: A reference to the security group for AppServers
    Value: !Ref AppserverSecurityGroup
